config/routes.rb
Gaultmillau::Application.routes.draw do
  get "/current-user-meta" => "home#current_user_meta", :as => "home_current_user_meta"

  namespace :admin do
    resources :posts, :path => 'tartalommenedzser' do
      resources :blocks
      get :autocomplete_tag_name, :on => :collection
    end

    resources :home_blocks, :path => 'cimlapszerkeszto'
    resources :comments, :path => 'hozzaszolasok'
    resources :orders, :path => 'rendelesek', :only => [:index, :edit, :update, :destroy]
    resources :restaurant_reservations, :path => 'asztalfoglalasok', :only => [:index, :show, :destroy]
    resources :tags, :path => 'cimkek', :only => [:index, :destroy, :update, :edit, :show]
    resources :attachments, :path => 'mellekletek'
    resources :products, :path => 'termekek'
    resources :users, :path => 'felhasznalok' do
      member do
        get 'manual_confirm'
      end
    end

    post "/admin/home_blocks/sort" => "home_blocks#sort", :as => "sort_home_blocks"
    get "/admin/posts/:id/edit_post_meta" => "posts#edit_post_meta", :as => "edit_post_meta"
    post "/admin/blocks/sort" => "blocks#sort", :as => "sort_blocks"
    get "/admin/js/recipes_list" => "posts#recipes_list", :as => "recipes_list"
  end

  get "/admin" => "admin#index", :as => "admin_index"

  devise_for :users,
             :path => 'felhasznalok',
             :path_names => {
               :sign_up => 'regisztracio',
               :sign_in => 'bejelentkezes',
               :sign_out => 'kijelentkezes'
             }, :controllers => { :registrations => "registrations" }

  resources :products, :path => 'termekek', :only => [:show, :index] do
    resources :orders, :path => 'rendelesek', :only => [:create, :new, :index]
  end

  get 'rendelesek/:token', to: 'orders#show', as: :order

  resources :newsletter_subscriptions, :path => 'hirlevel'
  get 'hirlevel/jovahagyas/:id', to: 'newsletter_subscriptions#confirm', :as => 'confirm_newsletter_subscription'
  get 'hirlevel/leiratkozas/:id', to: 'newsletter_subscriptions#confirm_unsubscribe', :as => 'confirm_newsletter_unsubscribe'

  resources :feedbacks, :path => 'kapcsolat', :only => [:create]
  get 'kapcsolat', to: 'feedbacks#new', :as => 'new_feedback'

  resources :favourites, :path => 'kedvencek', :only => [:create, :update]

  get '/ettermek/legjobbak', to: 'restaurants#best_of_map', as: :best_of_restaurants_map
  get '/szallodak/legjobbak', to: 'hotels#best_of_map', as: :best_of_hotels_map
  get '/boraszatok/legjobbak', to: 'wineries#best_of_map', as: :best_of_wineries_map
  get '/ettermek/budapest-extra', to: 'restaurants#additional', as: :additional

  resources :restaurants, :path => 'ettermek' do
    get :autocomplete_restaurant_search_cache_name, :on => :collection
  end

  resources :hotels, :path => 'szallodak'
  resources :wineries, :path => 'boraszatok'

  resources :amuva_posts, :path => 'muvelt-alkoholista' do
    resources :amuva_comments
  end

  resources :bsz_posts, :path => 'buvos-szakacs' do
    resources :bsz_comments
  end

  resources :mh_posts, :path => 'mese-habbal' do
    resources :mh_comments
  end

  resources :news, :path => 'gm-magazin' do
    resources :news_comments
  end

  resources :restaurant_reservations, :path => 'ettermek/asztalfoglalas', :only => [:index, :new, :create]
  get 'asztalfoglalas/jovahagyas/:id', to: 'restaurant_reservations#confirm', :as => 'confirm_restaurant_reservation'

  get '/muvelt-alkoholista/cimke/:tag', to: 'amuva_posts#index', as: :amuva_tag
  get '/buvos-szakacs/cimke/:tag', to: 'bsz_posts#index', as: :bsz_tag
  get '/gm-magazin/cimke/:tag', to: 'news#index', as: :news_tag
  get '/mese-habbal/cimke/:tag', to: 'mh_posts#index', as: :mh_tag

  get '/feed', to: 'home#feed', as: :home_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista', to: 'amuva_posts#index', as: :amuva_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista/kommentek', to: 'amuva_comments#index', as: :amuva_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs', to: 'bsz_posts#index', as: :bsz_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs/kommentek', to: 'bsz_comments#index', as: :bsz_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal', to: 'mh_posts#index', as: :mh_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal/kommentek', to: 'mh_comments#index', as: :mh_comments_feed, :defaults => { :format => 'rss' }

  resources :recipes, :path => 'receptek'

  get '/kereses', to: 'search#index', as: :search

  # Redirects
  get '/c/:id', to: 'short_urls#show', :as => 'short_url'
  get '/reg', to: redirect('felhasznalok/regisztracio')
  get '/regisztracio', to: redirect('felhasznalok/regisztracio')
  get '/bejelentkezes', to: redirect('felhasznalok/bejelentkezes')
  get '/fiok', to: redirect('felhasznalok/edit')
  get '/fiokom', to: redirect('felhasznalok/edit')
  get '/kod', to: redirect('a-gault-and-millau-2015-os-kalauz-nyomtatott-kuponkodjainak-bevaltasa')

  # Root and Pages

  get '/kalauz-2012/', to: 'guides2012#index', as: :guides2012
  get '/kalauz-2012/:id', to: 'guides2012#show', as: :guide2012
  get '/kalauz-2013/', to: 'guides2013#index', as: :guides2013
  get '/kalauz-2013/:id', to: 'guides2013#show', as: :guide2013
  get '/kalauz-2014/', to: 'guides2014#index', as: :guides2014
  get '/kalauz-2014/:id', to: 'guides2014#show', as: :guide2014
  get '/kalauz-2015/', to: 'guides2015#index', as: :guides2015
  get '/kalauz-2015/:id', to: 'guides2015#show', as: :guide2015
  get '/kalauz-2016/', to: 'guides2016#index', as: :guides2016
  get '/kalauz-2016/:id', to: 'guides2016#show', as: :guide2016
  get '/kalauz-2017/', to: 'guides2017#index', as: :guides2017
  get '/kalauz-2017/:id', to: 'guides2017#show', as: :guide2017
  get ':id', to: 'pages#show', as: :page

  root :to => "home#index"
end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :post, :touch => true
  belongs_to :attachment
  acts_as_list scope: :post

  has_paper_trail :on => [:update, :destroy]

  scope :parent_posts, lambda { |post_id| where(:content => "#{post_id}") unless post_id.blank? }
  scope :attachment_blocks, lambda { where :kind => 'image' }

  def self.text_kind_options
    [[I18n.t('admin.posts.block_options.kind.text'), 'text'],
     [I18n.t('admin.posts.block_options.kind.title'), 'title'],
     [I18n.t('admin.posts.block_options.kind.bordered_text'), 'bordered-text']]
  end

  def self.kind_options
    self.text_kind_options + [[I18n.t('admin.posts.block_options.kind.image'), 'image'],
                              [I18n.t('admin.posts.block_options.kind.video'), 'video'],
                              [I18n.t('admin.posts.block_options.kind.recipe'), 'recipe'],
                              [I18n.t('admin.posts.block_options.kind.post'), 'post']]
  end

  def self.image_class_options
    [['Alap', 'default'],
     ['Középre zárt', 'centered'],
     ['Teljes', 'full-width']]
  end
end

app/controllers/admin/blocks_controller.rb
class Admin::BlocksController < ApplicationController
  include Concerns::Administrable
  before_filter :authenticate_user!, :show_not_found_for_non_admins

  def show
    @post = Post.find(params[:post_id])
    @block = @post.blocks.find(params[:id])
    authorize @post

    respond_to do |format|
      format.js
    end
  end

  def new
    @post = Post.find(params[:post_id])
    @block = @post.blocks.new
    authorize @post

    respond_to do |format|
      format.js
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @block = @post.blocks.find(params[:id])
    authorize @post

    respond_to do |format|
      format.js
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @block = @post.blocks.new(block_params)
    authorize @post

    @block.save
    @block.move_to_bottom
    respond_to do |format|
      format.js
    end
  end

  def update
    @post = Post.find(params[:post_id])
    @block = @post.blocks.find(params[:id])
    authorize @post

    @block.update(block_params)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @block = @post.blocks.find(params[:id])
    authorize @post

    if @block.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  def sort
    params[:block].each_with_index do |id, index|
      Block.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

  private
    def block_params
      params.require(:block).permit(:content, :kind, :attachment_id, :css_class, :restaurant_id, :post_id)
    end
end

app/helpers/admin/blocks_helper.rb
module Admin::BlocksHelper
end

app/views/admin/blocks/_block.html.erb
<%= content_tag_for :li, block, 'data-block-id' => block.id do %>
  <div class="row">
    <div class="eight columns centered">
      <div class="actions">
        <%= link_to t('admin.posts.actions.blocks.destroy'), [:admin, post, block], :remote => true, method: :delete, data: { confirm: "Biztos törli ezt a dobozt?" }, :class => 'delete', :title => t('admin.posts.actions.blocks.destroy') %>
        <%= link_to t('admin.posts.actions.blocks.edit'), edit_admin_post_block_path(post, block), :remote => true, :class => 'edit', :title => t('admin.posts.actions.blocks.edit') %>
        <%= content_tag :span, t('admin.posts.actions.blocks.move'), :class => 'handle drag' %>
      </div>
      <% if block.kind == 'title' %>
        <h2><%= block.content.nil? || block.content.empty? ? content_tag(:p, t('admin.posts.messages.notices.blocks.empty_text'), :class => 'info-panel error') : block.content %></h2>
      <% end %>
      <% if block.kind == 'text' %>
        <%= markdown block.content.nil? || block.content.empty? ? content_tag(:p, t('admin.posts.messages.notices.blocks.empty_text'), :class => 'info-panel error') : block.content %>
      <% end %>
      <% if block.kind == 'bordered-text' %>
        <div class="bordered-text">
          <%= markdown block.content.nil? || block.content.empty? ? content_tag(:p, t('admin.posts.messages.notices.blocks.empty_text'), :class => 'info-panel error') : block.content %>
        </div>
      <% end %>
      <% if block.kind == 'big-text' %>
        <div class="big-text">
          <%= markdown block.content.nil? || block.content.empty? ? content_tag(:p, t('admin.posts.messages.notices.blocks.empty_text'), :class => 'info-panel error') : block.content %>
        </div>
      <% end %>
      <% if block.kind == 'image' %>
        <% if !block.attachment_id.nil? %>
          <figure class="<%= block.css_class %>">
            <%= image_tag processed_attachment_url(block.attachment, :medium), :size => block.attachment.attachment.image_size(:medium), :style => "background-color: #{block.attachment.average_color}" %>
            <% if !block.content.empty? %>
              <figcaption><%= block.content %></figcaption>
            <% end %>
          </figure>
        <% else %>
          <p class="info-panel error"><%= t('admin.posts.messages.notices.blocks.empty_image') %></p>
        <% end %>
      <% end %>
      <% if block.kind == 'video' %>
        <div class="embedded-video">
          <iframe src="http://player.vimeo.com/video/<%= block.content %>?byline=0&color=F2B500" width="720" height="405" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
        </div>
      <% end %>
      <% if block.kind == 'recipe' %>
        <div class="embedded-post recipe">
          <%= link_to_recipe(block) %>
        </div>
      <% end %>
      <% if block.kind == 'post' %>
        <div class="embedded-post post">
          <%= link_to_post(block) %>
        </div>
      <% end %>
      <% if block.kind == 'restaurant' %>
        <div class="embedded-post restaurant">
          <%= link_to_restaurant(block) %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/blocks/_form.html.erb
<%= content_tag_for :li, block, :class => 'edit', 'data-block-id' => block.id do %>
  <div class="row">
    <div class="eight columns centered">
      <%= form_tag admin_attachments_path, :method => :get, :remote => 'true', :id => "attachment-search-form-#{block.id}", 'data-behavior' => "attachment-search-form-#{block.id}", :class => 'hidden' do %>
        <%= hidden_field_tag :block_id, block.id %>
      <% end %>
      <%= form_for [:admin, post, block], :html => { :class => 'block-form', 'data-behavior' => 'block-form', :remote => true } do |f| %>
        <% if block.new_record? %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.new') %></p>
          <%= f.select :kind, options_for_select(Block.kind_options), {},  {} %>
        <% end %>
        <% if block.kind == 'title' %>
          <p><%= f.text_field :content, :placeholder => t('admin.posts.placeholders.blocks.title'), :autofocus => true %></p>
          <%= f.select :kind, options_for_select(Block.text_kind_options, :selected => block.kind), {},  {} %>
        <% end %>
        <% if block.kind == 'text' %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.text_format_options').html_safe %></p>
          <p><%= f.text_area :content, :rows => 8, :placeholder => t('admin.posts.placeholders.blocks.text_content'), :autofocus => true %></p>
          <%= f.select :kind, options_for_select(Block.text_kind_options, :selected => block.kind), {},  {} %>
        <% end %>
        <% if block.kind == 'big-text' %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.text_format_options').html_safe %></p>
          <p><%= f.text_area :content, :rows => 8, :placeholder => t('admin.posts.placeholders.blocks.text_content'), :autofocus => true %></p>
          <%= f.select :kind, options_for_select(Block.text_kind_options, :selected => block.kind), {},  {} %>
        <% end %>
        <% if block.kind == 'bordered-text' %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.text_format_options').html_safe %></p>
          <p><%= f.text_area :content, :rows => 8, :placeholder => t('admin.posts.placeholders.blocks.text_content'), :autofocus => true %></p>
          <%= f.select :kind, options_for_select(Block.text_kind_options, :selected => block.kind), {},  {} %>
        <% end %>
        <% if block.kind == 'image' %>
          <div class="attachment-browser" data-behavior="attachment-browser-<%= block.id %>">
            <%= link_to 'Válasszon a mellékletekből…', admin_attachments_path(:category => session[:last_attachment_picker_filter], :block_id => block.id), :remote => true, :class => 'open-attachment-browser' %>
          </div>
          <%= f.hidden_field :attachment_id, 'data-behavior' => 'attachment-id' %>
          <div class="attachment-options">
            <div class="attachment-preview">
              <% unless block.attachment_id.nil? %>
                <%= image_tag processed_attachment_url(block.attachment, :medium), 'data-behavior' => 'attachment-preview' %>
              <% else %>
                <%= image_tag 'transparent.png', 'data-behavior' => 'attachment-preview' %>
              <% end %>
            </div>
            <div class="attachment-fields">
              <% for image_class in Block.image_class_options %>
                <div class="row">
                  <div class="twelve columns">
                    <div class="radio-button">
                      <%= f.radio_button :css_class, image_class[1] %>
                      <%= f.label "css_class_#{image_class[1]}", image_class[0] %>
                    </div>
                  </div>
                </div>
              <% end %>
              <%= f.label :content, 'Képaláírás:' %>
              <%= f.text_field :content, :placeholder => t('admin.posts.placeholders.blocks.image_content') %>
            </div>
          </div>
        <% end %>
        <% if block.kind == 'video' %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.choose_video').html_safe %></p>
          <%= f.text_field :content %>
        <% end %>
        <% if block.kind == 'recipe' %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.choose_recipe') %></p>
          <%= f.select :content, options_for_select(find_all_recipe, :selected => block.content), {},  { 'data-behavior' => 'choose-post' } %>
        <% end %>
        <% if block.kind == 'post' %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.choose_post') %></p>
          <%= f.select :content, options_for_select(find_all_post(block), :selected => block.content), {},  { 'data-behavior' => 'choose-post' } %>
        <% end %>
        <% if block.kind == 'restaurant' %>
          <p class="info-panel"><%= t('admin.posts.messages.info_panels.blocks.choose_restaurant') %></p>
          <%= f.select :restaurant_id, options_for_select(find_all_restaurants, :selected => block.restaurant_id), {},  { 'data-behavior' => 'choose-post' } %>
        <% end %>
        <div class="form-actions">
          <%= f.submit block.new_record? ? t('admin.posts.actions.blocks.new') : t('admin.posts.actions.blocks.update') %>
          <% unless block.new_record? %>
            <%= t('shared.messages.or') %> <%= link_to t('shared.actions.cancel'), admin_post_block_path(post, block), :remote => true %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/blocks/create.js.erb
$('#new_block').remove();
$('[data-behavior~=new-block]').before('<%=j render :partial => 'admin/blocks/form', :locals => { :post => @post, :block => @block } %>');
$('[data-block-id~=<%= @block.id %>] textarea').autosize({ append: '' });
if ($('[data-behavior~=choose-post]').length > 0) {
  $("[data-behavior~=choose-post]").chosen({
    width: "100%",
    no_results_text: "<%= t('admin.posts.messages.notices.blocks.post_not_found') %>"
  });
}
$('html').addClass('loaded');

app/views/admin/blocks/destroy.js.erb
$('[data-block-id~=<%= @block.id %>]').fadeOut(300);
$('html').addClass('loaded');

app/views/admin/blocks/edit.js.erb
$('[data-block-id~=<%= @block.id %>]').replaceWith('<%= j render :partial => 'admin/blocks/form', :locals => { :post => @post, :block => @block } %>');
$('[data-block-id~=<%= @block.id %>] textarea').autosize({ append: '' });
if ($('[data-behavior~=choose-post]').length > 0) {
  $("[data-behavior~=choose-post]").chosen({
    width: "100%",
    no_results_text: "<%= t('admin.posts.messages.notices.blocks.post_not_found') %>"
  });
}
$('html').addClass('loaded');

app/views/admin/blocks/new.js.erb
if ($('#new_block').length == 0) {
  $('[data-behavior~=new-block]').before('<%= j render :partial => 'admin/blocks/form', :locals => { :post => @post, :block => @block } %>')
}

$("form[data-behavior~=attachment-search-form] input, form[data-behavior~=attachment-search-form] select").on("change", function() {
  return $(this).parents("form[data-behavior~=table-form]").submit();
});
$('html').addClass('loaded');

app/views/admin/blocks/show.js.erb
$('[data-block-id~=<%= @block.id %>]').replaceWith('<%= j render :partial => 'admin/blocks/block', :locals => { :post => @post, :block => @block } %>');
$('html').addClass('loaded');

app/views/admin/blocks/update.js.erb
$('[data-block-id~=<%= @block.id %>]').replaceWith('<%= j render :partial => 'admin/blocks/block', :locals => { :post => @post, :block => @block } %>');
$('[data-block-id~=<%= @block.id %>]').effect("highlight", {color: '#feffe6'}, 500);
$('html').addClass('loaded');