config/routes.rb
Gaultmillau::Application.routes.draw do
  get "/current-user-meta" => "home#current_user_meta", :as => "home_current_user_meta"

  namespace :admin do
    resources :posts, :path => 'tartalommenedzser' do
      resources :blocks
      get :autocomplete_tag_name, :on => :collection
    end

    resources :home_blocks, :path => 'cimlapszerkeszto'
    resources :comments, :path => 'hozzaszolasok'
    resources :orders, :path => 'rendelesek', :only => [:index, :edit, :update, :destroy]
    resources :restaurant_reservations, :path => 'asztalfoglalasok', :only => [:index, :show, :destroy]
    resources :tags, :path => 'cimkek', :only => [:index, :destroy, :update, :edit, :show]
    resources :attachments, :path => 'mellekletek'
    resources :products, :path => 'termekek'
    resources :users, :path => 'felhasznalok' do
      member do
        get 'manual_confirm'
      end
    end

    post "/admin/home_blocks/sort" => "home_blocks#sort", :as => "sort_home_blocks"
    get "/admin/posts/:id/edit_post_meta" => "posts#edit_post_meta", :as => "edit_post_meta"
    post "/admin/blocks/sort" => "blocks#sort", :as => "sort_blocks"
    get "/admin/js/recipes_list" => "posts#recipes_list", :as => "recipes_list"
  end

  get "/admin" => "admin#index", :as => "admin_index"

  devise_for :users,
             :path => 'felhasznalok',
             :path_names => {
               :sign_up => 'regisztracio',
               :sign_in => 'bejelentkezes',
               :sign_out => 'kijelentkezes'
             }, :controllers => { :registrations => "registrations" }

  resources :products, :path => 'termekek', :only => [:show, :index] do
    resources :orders, :path => 'rendelesek', :only => [:create, :new, :index]
  end

  get 'rendelesek/:token', to: 'orders#show', as: :order

  resources :newsletter_subscriptions, :path => 'hirlevel'
  get 'hirlevel/jovahagyas/:id', to: 'newsletter_subscriptions#confirm', :as => 'confirm_newsletter_subscription'
  get 'hirlevel/leiratkozas/:id', to: 'newsletter_subscriptions#confirm_unsubscribe', :as => 'confirm_newsletter_unsubscribe'

  resources :feedbacks, :path => 'kapcsolat', :only => [:create]
  get 'kapcsolat', to: 'feedbacks#new', :as => 'new_feedback'

  resources :favourites, :path => 'kedvencek', :only => [:create, :update]

  get '/ettermek/legjobbak', to: 'restaurants#best_of_map', as: :best_of_restaurants_map
  get '/szallodak/legjobbak', to: 'hotels#best_of_map', as: :best_of_hotels_map
  get '/boraszatok/legjobbak', to: 'wineries#best_of_map', as: :best_of_wineries_map
  get '/ettermek/budapest-extra', to: 'restaurants#additional', as: :additional

  resources :restaurants, :path => 'ettermek' do
    get :autocomplete_restaurant_search_cache_name, :on => :collection
  end

  resources :hotels, :path => 'szallodak'
  resources :wineries, :path => 'boraszatok'

  resources :amuva_posts, :path => 'muvelt-alkoholista' do
    resources :amuva_comments
  end

  resources :bsz_posts, :path => 'buvos-szakacs' do
    resources :bsz_comments
  end

  resources :mh_posts, :path => 'mese-habbal' do
    resources :mh_comments
  end

  resources :news, :path => 'gm-magazin' do
    resources :news_comments
  end

  resources :restaurant_reservations, :path => 'ettermek/asztalfoglalas', :only => [:index, :new, :create]
  get 'asztalfoglalas/jovahagyas/:id', to: 'restaurant_reservations#confirm', :as => 'confirm_restaurant_reservation'

  get '/muvelt-alkoholista/cimke/:tag', to: 'amuva_posts#index', as: :amuva_tag
  get '/buvos-szakacs/cimke/:tag', to: 'bsz_posts#index', as: :bsz_tag
  get '/gm-magazin/cimke/:tag', to: 'news#index', as: :news_tag
  get '/mese-habbal/cimke/:tag', to: 'mh_posts#index', as: :mh_tag

  get '/feed', to: 'home#feed', as: :home_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista', to: 'amuva_posts#index', as: :amuva_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista/kommentek', to: 'amuva_comments#index', as: :amuva_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs', to: 'bsz_posts#index', as: :bsz_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs/kommentek', to: 'bsz_comments#index', as: :bsz_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal', to: 'mh_posts#index', as: :mh_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal/kommentek', to: 'mh_comments#index', as: :mh_comments_feed, :defaults => { :format => 'rss' }

  resources :recipes, :path => 'receptek'

  get '/kereses', to: 'search#index', as: :search

  # Redirects
  get '/c/:id', to: 'short_urls#show', :as => 'short_url'
  get '/reg', to: redirect('felhasznalok/regisztracio')
  get '/regisztracio', to: redirect('felhasznalok/regisztracio')
  get '/bejelentkezes', to: redirect('felhasznalok/bejelentkezes')
  get '/fiok', to: redirect('felhasznalok/edit')
  get '/fiokom', to: redirect('felhasznalok/edit')
  get '/kod', to: redirect('a-gault-and-millau-2015-os-kalauz-nyomtatott-kuponkodjainak-bevaltasa')

  # Root and Pages

  get '/kalauz-2012/', to: 'guides2012#index', as: :guides2012
  get '/kalauz-2012/:id', to: 'guides2012#show', as: :guide2012
  get '/kalauz-2013/', to: 'guides2013#index', as: :guides2013
  get '/kalauz-2013/:id', to: 'guides2013#show', as: :guide2013
  get '/kalauz-2014/', to: 'guides2014#index', as: :guides2014
  get '/kalauz-2014/:id', to: 'guides2014#show', as: :guide2014
  get '/kalauz-2015/', to: 'guides2015#index', as: :guides2015
  get '/kalauz-2015/:id', to: 'guides2015#show', as: :guide2015
  get '/kalauz-2016/', to: 'guides2016#index', as: :guides2016
  get '/kalauz-2016/:id', to: 'guides2016#show', as: :guide2016
  get '/kalauz-2017/', to: 'guides2017#index', as: :guides2017
  get '/kalauz-2017/:id', to: 'guides2017#show', as: :guide2017
  get ':id', to: 'pages#show', as: :page

  root :to => "home#index"
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  has_many :blocks
  has_many :posts
  validates :attachment, :category, :presence => true

  has_attached_file :attachment, :styles => { :small => "200x200>", :medium => "1500x10000>" }
  process_in_background :attachment, :processing_image_url => "/assets/processing.png"

  validates_attachment_size :attachment, :less_than => 10.megabytes
  validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'application/msword']

  default_scope { order("created_at DESC") }
  scope :by_categories, lambda { |category|
    if category == 'latest'
      where(:created_at => Date.today) unless category.blank?
    else
      where(:category => category) unless category.blank?
    end
  }
  scope :by_empty_category, lambda { where('category is null OR category = ?', "") }
  scope :by_keyword, lambda { |keyword| where('title ilike ?', "%#{keyword}%") unless keyword.blank? }

  before_post_process :only_images
  before_create :default_name, :get_average_color

  def only_images
    %w(image/jpeg image/png image/gif).include?(attachment_content_type)
  end

  def default_name
    self.title ||= self.attachment_file_name
  end

  def get_average_color
    if %w(image/jpeg image/png image/gif).include?(attachment_content_type)
      tempfile = attachment.queued_for_write[:original]
      image = Magick::Image.read(tempfile.path).first
      if image.alpha?
        self.average_color = "transparent"
      else
        self.average_color = calculate_average_color image
      end
    end
  end


  def calculate_average_color image
    total = 0
    avg = { :r => 0.0, :g => 0.0, :b => 0.0 }

    image.quantize.color_histogram.each do |c,n|
      avg[:r] += n * c.red
      avg[:g] += n * c.green
      avg[:b] += n * c.blue
      total += n
    end

    avg.each_key do |c|
      avg[c] /= total
      avg[c] = (avg[c] / Magick::QuantumRange * 255).to_i
    end

    return "rgb(#{avg[:r]},#{avg[:g]},#{avg[:b]})"
  end

  def self.maximum_file_size
    10.megabytes
  end

  def self.categories
    [['Művelt Alkoholista', 'a-muvelt-alkoholista'],
     ['Bűvös Szakács', 'buvos-szakacs'],
     ['Mese Habbal', 'mese-habbal'],
     ['G&M Magazin', 'hirek'],
     ['Receptek', 'receptek'],
     ['Címlapfotók', 'cimlapfotok'],
     ['Oldalak', 'oldalak'],
     ['Egyéb', 'egyeb']]
  end

  def self.reprocess_attachments!
    Attachment.find_each do |a|
      begin
        a.attachment.reprocess!
        puts "Scheduled attachment #{a.id} for reprocessing"
      rescue
        puts "Skipped attachment #{a.id} while reprocessing"
        next
      end
    end
  end
end

app/controllers/admin/attachments_controller.rb
class Admin::AttachmentsController < ApplicationController
  include Concerns::Administrable

  before_filter :authenticate_user!, :show_not_found_for_non_admins
  layout "admin"

  def index
    @attachment = Attachment.new
    @attachments = Attachment.by_categories(params[:category]).order('created_at DESC').paginate(:per_page => 28, :page => params[:page])
    @attachments_picker = Attachment.by_keyword(params[:keyword]).by_categories(params[:category]).order('created_at DESC').paginate(:per_page => 28, :page => params[:page])
    @attachment_months = @attachments_picker.group_by { |a| a.created_at.beginning_of_month }

    session[:last_attachment_picker_filter] = params[:category]

    authorize @attachments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
      format.js
    end
  end

  def show
    @attachment = Attachment.find(params[:id])
    authorize @attachment

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  def new
    @attachment = Attachment.new
    authorize @attachment

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  def edit
    @attachment = Attachment.find(params[:id])
    authorize @attachment
  end

  def create
    @attachment = Attachment.new(attachment_params)
    authorize @attachment

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to admin_attachments_url(:category => @attachment.category), notice: t('admin.attachments.messages.notices.created') }
        format.json { render json: @attachment, status: :created, location: @attachment }
        if params[:dropped_from_editor]
          @block = Block.new
          @block.kind = 'image'
          @block.css_class = 'default'
          @block.content = ' '
          @block.attachment = @attachment
          @block.post_id = params[:post_id]
          @block.save
          format.js
        end
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @attachment = Attachment.find(params[:id])
    authorize @attachment

    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to admin_attachments_url(:category => @attachment.category), notice: t('admin.attachments.messages.notices.updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @attachment = Attachment.find(params[:id])
    authorize @attachment
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to admin_attachments_url, notice: t('admin.attachments.messages.notices.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    def attachment_params
      params.require(:attachment).permit(:title, :attachment, :category)
    end
end

app/helpers/admin/attachments_helper.rb
module Admin::AttachmentsHelper
  def current_attachment_category(params)
    Attachment.categories.select do |s|
      if s.include? params[:category]
        return s[0].to_s
      end
    end
  end

  def current_attachment_category_count(params)
    format_count(Attachment.by_categories(params[:category]).size)
  end

  def currently_processing_attachments?
    job = Delayed::Job.last

    if job && job.payload_object.class == DelayedPaperclip::Jobs::DelayedJob
      true
    else
      false
    end
  end

  def processed_attachment_url attachment, size = :small
    if !attachment.nil?
      if attachment.attachment.processing?
        "#{ENV['RACKSPACE_HOST']}/attachments/#{attachment.id}/original/#{attachment.attachment_file_name}"
      else
        attachment.attachment.url(size)
      end
    end
  end
end

app/views/admin/attachments/_attachment.html.erb
<% cache ['v13', attachment] do %>
  <div class="three columns attachment-container end">
    <%= link_to edit_admin_attachment_path(attachment), :class => 'attachment', 'style' => "background-image: url('#{processed_attachment_url(attachment)}'); background-color: #{attachment.average_color};" do %>
      <%= content_tag :span, attachment.attachment_file_name + ' (' + number_to_human_size(attachment.attachment.size) + ')' %>
    <% end %>
  </div>
<% end %>

app/views/admin/attachments/_attachment_browser.html.erb
<div class="row">
  <div class="twelve columns">
    <ul class="plain horizontal attachment-category-filter clearfix category-<%= params[:category].blank? || params[:category] == 'latest' ? 'all' : params[:category] %>">
      <li><%= select_tag :category, "<option value=\"\">Minden modul</option>".html_safe + options_for_select(Attachment.categories, params[:category]), :class => 'select-field attachment-category-select', :form => "attachment-search-form-#{params[:block_id]}", 'data-behavior' => "attachment-category-select-#{params[:block_id]}" %></li>
      <li><%= text_field_tag :keyword, params[:keyword], :placeholder => t('shared.placeholders.filter_table'), :class => 'attachment-keyword-field', :form => "attachment-search-form-#{params[:block_id]}", 'data-behavior' => "attachment-keyword-field-#{params[:block_id]}" %></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="twelve columns">
    <div class="attachment-browser-container">
      <div class="attachment-browser-inner row">
        <% if !@attachments_picker.empty? %>
          <% @attachment_months.each do |month, attachments_picker| %>
            <h2 class="twelve columns attachments-months"><%= l(month, :format => :year_and_month) %></h2>
            <% for attachment in attachments_picker %>
              <% cache ['v15', 'attachment_picker', attachment] do %>
                <div class="two columns end <%= attachment.category %> attachment-picker-container">
                  <%= link_to processed_attachment_url(attachment, :medium), 'data-behavior' => 'attachment-selector', 'data-attachment-id' => attachment.id, :class => 'attachment-selector', 'style' => "background-image: url('#{processed_attachment_url(attachment)}'); background-color: #{attachment.average_color};" do %>
                    <span class="attachment-selector-title"><%= attachment.title %></span>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% else %>
          <div class="twelve columns">
            <p class="empty-attachments">Nem található melléklet ebben a kategóriában.</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="twelve columns text-centered">
      <div class="pagination-container">
        <%= page_navigation_links(@attachments_picker, true) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/attachments/_form.html.erb
<div class="twelve columns">
  <%= form_for([:admin, @attachment], :html => { :class => 'admin-form', :mutlipart => true }) do |f| %>
    <div class="row">
      <div class="six columns centered">
        <div class="row">
          <div class="four columns">
            <%= f.label :attachment, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <% if @attachment.new_record? %>
              <%= f.file_field :attachment, :class => 'inline-field' %>
            <% else %>
              <p>
                <%= link_to processed_attachment_url(@attachment, :original), :title => t('admin.attachments.actions.download'), :class => 'download has-tip tip-right' do %>
                  <%= image_tag processed_attachment_url(@attachment, :medium) %>
                <% end %>
              </p>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :category, :class => 'inline right' %>
          </div>
          <div class="five columns end">
            <%= f.select :category, options_for_select(Attachment.categories, :selected => @attachment.new_record? ? params[:category] : @attachment.category), {},  { :class => 'inline-field' } %>
          </div>
        </div>
        <% unless @attachment.new_record? %>
          <div class="row">
            <div class="four columns">
              <%= f.label :attachment_file_size, :class => 'inline right' %>
            </div>
            <div class="five columns end">
              <span class="data-label"><%= number_to_human_size(@attachment.attachment.size) %></span>
            </div>
          </div>
          <div class="row">
            <div class="four columns">
              <%= f.label :attachment_content_type, :class => 'inline right' %>
            </div>
            <div class="five columns end">
              <span class="data-label"><%= @attachment.attachment.content_type %></span>
            </div>
          </div>
          <div class="row">
            <div class="four columns">
              <%= f.label t('activerecord.attributes.attachment.url'), :class => 'inline right' %>
            </div>
            <div class="eight columns end">
              <textarea data-behavior="copy-paste-field" rows="5" class="copy-paste-field" readonly><%= processed_attachment_url(@attachment, :original) %></textarea>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="six columns centered">
        <div class="form-actions">
          <% unless @attachment.new_record? %>
            <% if !@attachment.blocks.empty? %>
              <p class="info-panel"><%= t('admin.attachments.messages.info_panels.included_in_post').html_safe %>
              <%= @attachment.blocks.map { |block| link_to block.post.title, "#{edit_admin_post_path(block.post)}#block_#{block.id}" }.join(', ').html_safe %></p>
            <% end %>
          <% end %>
          <%= f.submit @attachment.new_record? ? t('admin.attachments.actions.new') : t('admin.attachments.actions.update'), 'data-behavior' => 'save-button' %>
          <% unless @attachment.new_record? %>
            <% if @attachment.blocks.empty? %>
              <%= t('shared.messages.or') %> <%= link_to t('shared.actions.destroy'), [:admin, @attachment], method: :delete, data: { confirm: t('admin.attachments.messages.confirmations.destroy') } %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/attachments/create.js.erb
$('[data-behavior~=new-block]').before('<%= j render :partial => 'admin/blocks/block', :locals => { :post => @block.post, :block => @block } %>');
$('[data-block-id~=<%= @block.id %>]').effect("highlight", {color: '#feffe6'}, 500);

app/views/admin/attachments/edit.html.erb
<% content_for :title do %>
  <%= t('admin.attachments.titles.edit') %> &ndash; <%= t('admin.name') %> &ndash; <%= site_title %>
<% end  %>
<div class="row">
  <div class="three columns">
    <div class="action-group">
      <ul class="horizontal">
        <li><%= link_to t('admin.attachments.actions.back').html_safe, admin_attachments_path(:category => @attachment.category) %></li>
      </ul>
    </div>
  </div>
  <h2 class="six columns"><%= t('admin.attachments.titles.edit') %></span></h2>

  <%= render 'form' %>
</div>

app/views/admin/attachments/index.html.erb
<% content_for :title do %>
  <%= t('admin.attachments.name') %> &ndash; <%= t('admin.name') %> &ndash; <%= site_title %>
<% end  %>
<div class="row">
  <div class="twelve columns">
    <div class="row">
      <h2 class="eight columns">
        <%= t('admin.attachments.name') %>
        <% if !params[:category].blank? %>
          <span class="subtitle">
            <%= '/ ' + current_attachment_category(params) %>
          </span>
          <%= content_tag :span, "(#{current_attachment_category_count(params)})", :class => 'subtitle' %>
        <% end %>
      </h2>
      <div class="four columns">
        <div class="action-group">
          <ul class="horizontal right">
            <li><%= link_to t('admin.attachments.titles.new'), new_admin_attachment_path(:category => params[:category]) %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% if !params[:category].blank? %>
    <div class="twelve columns">
      <p class="info-panel"><%= t('admin.attachments.messages.info_panels.drop_instructions') %> <%= t('admin.attachments.messages.info_panels.file_types', :maximum_file_size => number_to_human_size(Attachment.maximum_file_size)).html_safe %></p>
    </div>
    <%= form_for([:admin, @attachment], :html => { :class => 'admin-form attachment-uploader', :mutlipart => true }) do |f| %>
      <%= f.file_field :attachment, 'data-behavior' => 'attachment-uploader', :class => 'attachment-uploader' %>
      <%= f.hidden_field :category, 'value' => params[:category].blank? ? 'inbox' : params[:category] %>
    <% end %>
  <% end %>
  <div class="twelve columns attachments" data-behavior="attachment-dropzone">
    <div class="row">
      <div class="twelve columns">
        <div class="row">
          <% if !@attachments.empty? %>
            <% if params[:category].blank? %>
              <% Attachment.categories.each do |category| %>
                <div class="three columns end attachment-container">
                  <%= link_to admin_attachments_path(:category => category[1]), :class => 'attachment category' do %>
                    <span><%= category[0] %></span>
                  <% end %>
                </div>
              <% end %>
            <% else %>
              <% @attachments.each do |attachment| %>
                <%= render attachment %>
              <% end %>
              <div class="twelve columns text-centered">
                <div class="pagination-container">
                  <%= page_navigation_links(@comments) %>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="eight columns centered empty-notice">
              <div class="flash-notice notice text-centered"><%= t('admin.attachments.messages.notices.empty_category') %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="attachment-progress" data-behavior="attachment-progress">
  <div class="attachment-progress-bar" data-behavior="attachment-progress-bar"></div>
  <div class="attachment-progress-info" data-behavior="attachment-progress-info"></div>
</div>

app/views/admin/attachments/index.js.erb
$('[data-behavior~=attachment-browser-<%= params[:block_id] %>]').html('<%=j(render :partial => 'attachment_browser') %>');
$('.pagination a').attr('data-remote', 'true');
$('[data-behavior~=block-form]').on('click', '[data-behavior~=attachment-selector]', function() {
  var image_id = $(this).attr('data-attachment-id');
  var image_url = $(this).attr('href');
  $('[data-behavior~=attachment-id]').val(image_id);
  $('[data-behavior~=attachment-preview]').attr('src', image_url);
  $('[data-behavior~=attachment-selector]').removeClass('selected-attachment');
  $(this).addClass('selected-attachment');
  return false;
});
$('html').addClass("loaded");

$("[data-behavior~=attachment-category-select-<%= params[:block_id] %>], [data-behavior~=attachment-keyword-field-<%= params[:block_id] %>]").on("change", function() {
  var attachment_search_form = $(this).attr('form')
  return $("#"+ attachment_search_form).submit();
});

app/views/admin/attachments/new.html.erb
<% content_for :title do %>
  <%= t('admin.attachments.titles.new') %> &ndash; <%= t('admin.name') %> &ndash; <%= site_title %>
<% end  %>
<div class="row">
  <div class="three columns">
    <div class="action-group">
      <ul class="horizontal">
        <li><%= link_to t('admin.attachments.actions.back').html_safe, admin_attachments_path(:category => @attachment.category) %></li>
      </ul>
    </div>
  </div>
  <h2 class="nine columns"><%= t('admin.attachments.titles.new') %></h2>
  <div class="six columns offset-by-three">
    <p class="info-panel"><%= t('admin.attachments.messages.info_panels.file_types', :maximum_file_size => number_to_human_size(Attachment.maximum_file_size)).html_safe %></p>
  </div>
  <%= render 'form' %>
</div>