config/routes.rb
Gaultmillau::Application.routes.draw do
  get "/current-user-meta" => "home#current_user_meta", :as => "home_current_user_meta"

  namespace :admin do
    resources :posts, :path => 'tartalommenedzser' do
      resources :blocks
      get :autocomplete_tag_name, :on => :collection
    end

    resources :home_blocks, :path => 'cimlapszerkeszto'
    resources :comments, :path => 'hozzaszolasok'
    resources :orders, :path => 'rendelesek', :only => [:index, :edit, :update, :destroy]
    resources :restaurant_reservations, :path => 'asztalfoglalasok', :only => [:index, :show, :destroy]
    resources :tags, :path => 'cimkek', :only => [:index, :destroy, :update, :edit, :show]
    resources :attachments, :path => 'mellekletek'
    resources :products, :path => 'termekek'
    resources :users, :path => 'felhasznalok' do
      member do
        get 'manual_confirm'
      end
    end

    post "/admin/home_blocks/sort" => "home_blocks#sort", :as => "sort_home_blocks"
    get "/admin/posts/:id/edit_post_meta" => "posts#edit_post_meta", :as => "edit_post_meta"
    post "/admin/blocks/sort" => "blocks#sort", :as => "sort_blocks"
    get "/admin/js/recipes_list" => "posts#recipes_list", :as => "recipes_list"
  end

  get "/admin" => "admin#index", :as => "admin_index"

  devise_for :users,
             :path => 'felhasznalok',
             :path_names => {
               :sign_up => 'regisztracio',
               :sign_in => 'bejelentkezes',
               :sign_out => 'kijelentkezes'
             }, :controllers => { :registrations => "registrations" }

  resources :products, :path => 'termekek', :only => [:show, :index] do
    resources :orders, :path => 'rendelesek', :only => [:create, :new, :index]
  end

  get 'rendelesek/:token', to: 'orders#show', as: :order

  resources :newsletter_subscriptions, :path => 'hirlevel'
  get 'hirlevel/jovahagyas/:id', to: 'newsletter_subscriptions#confirm', :as => 'confirm_newsletter_subscription'
  get 'hirlevel/leiratkozas/:id', to: 'newsletter_subscriptions#confirm_unsubscribe', :as => 'confirm_newsletter_unsubscribe'

  resources :feedbacks, :path => 'kapcsolat', :only => [:create]
  get 'kapcsolat', to: 'feedbacks#new', :as => 'new_feedback'

  resources :favourites, :path => 'kedvencek', :only => [:create, :update]

  get '/ettermek/legjobbak', to: 'restaurants#best_of_map', as: :best_of_restaurants_map
  get '/szallodak/legjobbak', to: 'hotels#best_of_map', as: :best_of_hotels_map
  get '/boraszatok/legjobbak', to: 'wineries#best_of_map', as: :best_of_wineries_map
  get '/ettermek/budapest-extra', to: 'restaurants#additional', as: :additional

  resources :restaurants, :path => 'ettermek' do
    get :autocomplete_restaurant_search_cache_name, :on => :collection
  end

  resources :hotels, :path => 'szallodak'
  resources :wineries, :path => 'boraszatok'

  resources :amuva_posts, :path => 'muvelt-alkoholista' do
    resources :amuva_comments
  end

  resources :bsz_posts, :path => 'buvos-szakacs' do
    resources :bsz_comments
  end

  resources :mh_posts, :path => 'mese-habbal' do
    resources :mh_comments
  end

  resources :news, :path => 'gm-magazin' do
    resources :news_comments
  end

  resources :restaurant_reservations, :path => 'ettermek/asztalfoglalas', :only => [:index, :new, :create]
  get 'asztalfoglalas/jovahagyas/:id', to: 'restaurant_reservations#confirm', :as => 'confirm_restaurant_reservation'

  get '/muvelt-alkoholista/cimke/:tag', to: 'amuva_posts#index', as: :amuva_tag
  get '/buvos-szakacs/cimke/:tag', to: 'bsz_posts#index', as: :bsz_tag
  get '/gm-magazin/cimke/:tag', to: 'news#index', as: :news_tag
  get '/mese-habbal/cimke/:tag', to: 'mh_posts#index', as: :mh_tag

  get '/feed', to: 'home#feed', as: :home_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista', to: 'amuva_posts#index', as: :amuva_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista/kommentek', to: 'amuva_comments#index', as: :amuva_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs', to: 'bsz_posts#index', as: :bsz_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs/kommentek', to: 'bsz_comments#index', as: :bsz_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal', to: 'mh_posts#index', as: :mh_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal/kommentek', to: 'mh_comments#index', as: :mh_comments_feed, :defaults => { :format => 'rss' }

  resources :recipes, :path => 'receptek'

  get '/kereses', to: 'search#index', as: :search

  # Redirects
  get '/c/:id', to: 'short_urls#show', :as => 'short_url'
  get '/reg', to: redirect('felhasznalok/regisztracio')
  get '/regisztracio', to: redirect('felhasznalok/regisztracio')
  get '/bejelentkezes', to: redirect('felhasznalok/bejelentkezes')
  get '/fiok', to: redirect('felhasznalok/edit')
  get '/fiokom', to: redirect('felhasznalok/edit')
  get '/kod', to: redirect('a-gault-and-millau-2015-os-kalauz-nyomtatott-kuponkodjainak-bevaltasa')

  # Root and Pages

  get '/kalauz-2012/', to: 'guides2012#index', as: :guides2012
  get '/kalauz-2012/:id', to: 'guides2012#show', as: :guide2012
  get '/kalauz-2013/', to: 'guides2013#index', as: :guides2013
  get '/kalauz-2013/:id', to: 'guides2013#show', as: :guide2013
  get '/kalauz-2014/', to: 'guides2014#index', as: :guides2014
  get '/kalauz-2014/:id', to: 'guides2014#show', as: :guide2014
  get '/kalauz-2015/', to: 'guides2015#index', as: :guides2015
  get '/kalauz-2015/:id', to: 'guides2015#show', as: :guide2015
  get '/kalauz-2016/', to: 'guides2016#index', as: :guides2016
  get '/kalauz-2016/:id', to: 'guides2016#show', as: :guide2016
  get '/kalauz-2017/', to: 'guides2017#index', as: :guides2017
  get '/kalauz-2017/:id', to: 'guides2017#show', as: :guide2017
  get ':id', to: 'pages#show', as: :page

  root :to => "home#index"
end

app/models/order.rb
class Order < ActiveRecord::Base
  include Tokenable
  belongs_to :user
  belongs_to :product

  validates :address, :city, :full_name, :postcode, :product_count, :presence => true
  validates :billing_name, :billing_postcode, :billing_city, :billing_address, :presence => true, :if => :billing_same_as_order?
  validates :product_count, :numericality => { :greater_than => 0, :only_integer => true }
  validates :payment_method, :inclusion => { :in => ['delivery', 'transfer'] }
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :message => I18n.t(:invalid)
  validates_uniqueness_of :token, :payment_token

  before_create :generate_token, :generate_payment_token, :check_billing_fields, :assign_default_status

  has_paper_trail :on => [:update, :destroy]

  default_scope { order('created_at DESC') }

  include PgSearch
  pg_search_scope :search_by_meta, against: [:address, :city, :email, :full_name, :phone, :postcode, :product_count, :billing_postcode, :billing_city, :billing_address, :billing_name, :billing_phone, :payment_token], associated_against: { :product => [:name] },
                  :using => { :tsearch => {:dictionary => 'hungarian', :prefix => true} }

  scope :for_user, lambda { |user| where(:user_id => user.id) unless user.blank? }
  scope :by_status, lambda { |status| where(:status => status) unless status.blank? }
  scope :by_payment_method, lambda { |payment_method| where(:payment_method => payment_method) unless payment_method.blank? }

  def full_address
    "#{postcode} #{city}, #{address}"
  end

  def full_billing_address
    "#{billing_postcode} #{billing_city}, #{billing_address}"
  end

  def billing_same_as_order?
    if billing_address_same_as_order_address == true
      false
    else
      true
    end
  end

  def check_billing_fields
    if billing_address_same_as_order_address == true
      self.billing_name = nil
      self.billing_phone = nil
      self.billing_postcode = nil
      self.billing_city = nil
      self.billing_address = nil
      self.vat_number = nil
    end
  end

  def generate_payment_token
    begin
      random = SecureRandom.uuid
      payment_token = random[0..5]
    end while Order.where(:payment_token => payment_token).exists?
    self.payment_token = payment_token
  end

  def assign_default_status
    self.status = "Új rendelés"
  end

  def total
    if self.product_count > self.product.free_delivery_from_quantity
      self.product.price * self.product_count
    else
      (self.product.price * self.product_count) + self.product.delivery_price
    end
  end

  def payment_method_label
    if self.payment_method == 'delivery'
      I18n.t('helpers.label.order.payment_methods.delivery')
    elsif self.payment_method == 'transfer'
      I18n.t('helpers.label.order.payment_methods.transfer')
    end
  end

  def is_transfer?
    self.payment_method == 'transfer'
  end

  def self.transfer_info
    I18n.t('orders.messages.transfer_info').html_safe
  end

  def self.filter_by_meta(keyword)
    if !keyword.blank?
      search_by_meta(keyword)
    else
      order('orders.created_at DESC')
    end
  end

  def self.options_for_status
    ['Új rendelés', 'Kipostázott', 'Kézbesítő átvette', 'Vevő átvette', 'Lemondott']
  end

  def self.options_for_payment_method
    [[I18n.t('helpers.label.order.payment_methods.delivery'), 'delivery'], [I18n.t('helpers.label.order.payment_methods.transfer'), 'transfer']]
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  include Concerns::Administrable
  include Orderable

  before_filter :authenticate_user!, :show_not_found_for_non_admins
  layout "admin"

  def index
    @orders = Order.filter_by_meta(params[:search]).by_payment_method(params[:payment_method]).by_status(params[:status]).paginate(:per_page => 25, :page => params[:page])
    @orders_not_paginated = Order.filter_by_meta(params[:search]).by_payment_method(params[:payment_method]).by_status(params[:status])
    authorize @orders
    respond_to do |format|
      format.html
      format.xls do
        stream = render_to_string(:template=>"admin/orders/index")
        send_data stream, filename: "gaultmillau_rendelesek_#{Time.now.strftime('%Y_%m_%d_%H_%M')}.xls", type: "application/xls"
      end
    end
  end

  def edit
    @order = Order.find(params[:id])
    authorize @order
  end

  def update
    @order = Order.find(params[:id])
    authorize @order
    @order.attributes = order_params

    respond_to do |format|
      if @order.save(:validate => false)
        format.html { redirect_to admin_orders_url, notice: t('admin.orders.messages.notices.updated') }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order = Order.find(params[:id])
    authorize @order
    @order.destroy

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: t('admin.orders.messages.notices.destroyed') }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :setup_order, only: [:index, :new, :create]

  include ApplicationHelper
  include Orderable

  def index
    redirect_to new_product_order_path @product
  end

  def show
    if params[:token]
      @order = Order.where(:token => params[:token]).first
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def new
    @order = @product.orders.new
  end

  def create
    @order = @product.orders.new(order_params)

    if user_signed_in?
      @order.user = current_user
    end

    respond_to do |format|
      if @order.save
        OrderMailer.order_confirmation(@order).deliver
        if @order.payment_method == 'transfer'
          format.html { redirect_to order_path(@order.token) }
        else
          format.html { redirect_to root_path, :flash => { :email => t('orders.messages.notices.created', :email => articalize(@order.email, 'uppercase')).html_safe } }
        end
      else
        format.html { render action: "new" }
      end
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def all_orders_count orders
    format_count(orders.count)
  end

  def css_class_for_order_status order
    case order.status
      when 'Új rendelés' then 'order-status new'
      when 'Kipostázott' then 'order-status mailed'
      when 'Kézbesítő átvette' then 'order-status received'
      when 'Vevő átvette' then 'order-status buyer-received'
      when 'Lemondott' then 'order-status resigned'
    end
  end

  def style_for_new_orders
    'hidden' if new_orders_count == 0
  end

  def new_orders_count
    Order.by_status('Új rendelés').count
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def orders_has_credit_card_payment?
    false
  end
end

app/views/admin/orders/_form.html.erb
<div class="twelve columns">
  <%= form_for([:admin, @order], :html => { :class => 'admin-form order-form' }) do |f| %>
    <script>
      $(function() {
        function addCurrencySeparators(nStr) {
          nStr += '';
          x = nStr.split('.');
          x1 = x[0];
          x2 = x.length > 1 ? '.' + x[1] : '';
          var rgx = /(\d+)(\d{3})/;
          while (rgx.test(x1)) {
            x1 = x1.replace(rgx, '$1' + ' ' + '$2');
          }
          return x1 + x2;
        }

        var order_price = <%= @order.product.price %>;
        var order_delivery_price = <%= @order.product.delivery_price %>;
        var order_free_delivery_from_quantity = <%= @order.product.free_delivery_from_quantity %>;

        $('[data-behavior~=order-product-count-field]').on('keyup change', function() {
          var order_product_count = $(this).val();
          if (order_product_count == '' || order_product_count == 0) {
            $('[data-behavior~=order-total-calculator]').html('0');
          } else if (order_product_count > order_free_delivery_from_quantity) {
            $('[data-behavior~=order-total-calculator]').html(addCurrencySeparators(order_price * order_product_count) + ' Ft');
          } else {
            $('[data-behavior~=order-total-calculator]').html(addCurrencySeparators((order_price * order_product_count) + order_delivery_price) + ' Ft');
          }
        });

      });
    </script>
    <div class="row">
      <div class="six columns centered">
        <div class="row">
          <div class="four columns">
            <%= f.label :status, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.select :status, options_for_select(Order.options_for_status, :selected => @order.status), {},  { :class => 'inline-field' } %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :product_name, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <% if @order.product.available? %>
              <span class="data-label"><%= link_to @order.product.name, policy(@order.product).edit? ? edit_admin_product_path(@order.product) : admin_orders_path(:search => @order.product.name) %></span>
            <% else %>
              <span class="data-label"><%= @order.product.name %> (<%= t('admin.products.messages.not_available') %>)</span>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :payment_token, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <span class="data-label"><%= @order.payment_token %></span>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :total, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <span class="data-label" data-behavior="order-total-calculator"><%= number_to_currency(@order.total) %></span>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :product_count, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.number_field :product_count, :min => '1', 'data-behavior' => 'order-product-count-field' %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :email, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :email %>
          </div>
        </div>
        <div class="row">
          <div class="four columns"><%= f.label :payment_method, :class => 'inline right' %></div>
          <div class="eight columns">
            <div class="radio-button">
              <%= f.radio_button :payment_method, 'delivery', :id => "payment_methods_delivery" %><%= label_tag "payment_methods_delivery", t('helpers.label.order.payment_methods.delivery') %>
            </div>
            <div class="radio-button">
              <%= f.radio_button :payment_method, 'transfer', :id => "payment_methods_transfer" %><%= label_tag "payment_methods_transfer", t('helpers.label.order.payment_methods.transfer') %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :post_identifier, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :post_identifier %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :comment, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_area :comment, :rows => 4 %>
          </div>
        </div>
        <div class="row">
          <div class="eight columns end offset-by-four">
            <div class="checkbox">
              <%= f.check_box :paid %> <%= f.label :paid %>
            </div>
          </div>
        </div>
        <div class="row">
          <h3 class="twelve columns"><%= t('orders.titles.order_address') %></h3>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :full_name, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :full_name %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :phone, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :phone %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :postcode, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :postcode %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :city, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :city %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :address, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :address %>
          </div>
        </div>
        <div class="row">
          <h3 class="twelve columns"><%= t('orders.titles.billing_address') %></h3>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :billing_name, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :billing_name %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :billing_phone, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :billing_phone %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :billing_postcode, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :billing_postcode %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :billing_city, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :billing_city %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :billing_address, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :billing_address %>
          </div>
        </div>
        <div class="row">
          <div class="four columns">
            <%= f.label :vat_number, :class => 'inline right' %>
          </div>
          <div class="eight columns end">
            <%= f.text_field :vat_number %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="six columns centered">
        <div class="form-actions">
          <%= f.submit t('admin.orders.actions.update'), 'data-behavior' => 'save-button' %>
          <% if policy(@order).destroy? %>
            <%= t('shared.messages.or') %>
            <%= link_to t('shared.actions.destroy'), [:admin, @order], method: :delete, data: { confirm: t('admin.orders.messages.confirmations.destroy') } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/orders/_order.html.erb
<% cache ['v72', order] do %>
  <tr data-order-id="<%= order.id %>" class="<%= css_class_for_order_status order %>">
    <td class="title">
      <%= link_to order.full_name, edit_admin_order_path(order), :class => 'username' %>
    </td>
    <td>
      <%= form_for([:admin, order], :html => { :class => 'admin-form order-form', 'data-behavior' => 'table-form', :remote => true }) do |f| %>
        <span class="order-status-select-container">
          <%= f.select :status, options_for_select(Order.options_for_status, :selected => order.status), {},  { :class => 'inline-field' } %>
        </span>
        <span class="checkbox order-paid-checkbox-container">
          <span class="checkbox-icon order-paid">
            <%= f.check_box :paid, :id => "order_#{order.id}_paid", 'data-behavior' => 'order-paid-checkbox', :title => t('activerecord.attributes.order.paid') %> <%= f.label :paid, :for => "order_#{order.id}_paid" %>
          </span>
        </span>
      <% end %>
    </td>
    <td class="text-centered">
      <%= format_count order.product_count %> / <%= number_to_currency(order.total) %>
      <%= content_tag(:span, '', :class => 'order-icon post-identifier', :title => t('activerecord.attributes.order.post_identifier')) unless order.post_identifier.blank? %>
      <%= content_tag(:span, '', :class => 'order-icon comment', :title => t('activerecord.attributes.order.comment')) unless order.comment.blank? %>
    </td>
    <td class="text-centered"><%= link_to order.product.name, admin_orders_path(:search => order.product.name) %></td>
    <td class="text-centered"><%= order.payment_method_label %></td>
    <td class="text-centered"><time><%= l order.created_at, :format => :short %></time></td>
    <td class="text-centered"><%= order.payment_token %></td>
  </tr>
<% end %>

app/views/admin/orders/edit.html.erb
<% content_for :title do %>
  <%= t('admin.orders.titles.edit') %> &ndash; <%= t('admin.name') %> &ndash; <%= site_title %>
<% end  %>
<div class="row">
  <div class="three columns">
    <div class="action-group">
      <ul class="horizontal">
        <li><%= link_to t('admin.orders.actions.back').html_safe, admin_orders_path() %></li>
      </ul>
    </div>
  </div>
  <h2 class="six columns end"><%= t('admin.orders.titles.edit') %></h2>

  <%= render 'form' %>
</div>

app/views/admin/orders/index.html.erb
<% content_for :title do %>
  <%= t('admin.orders.name') %> &ndash; <%= t('admin.name') %> &ndash; <%= site_title %>
<% end  %>
<div class="row">
  <div class="twelve columns">
    <div class="row">
      <h2 class="four columns"><%= t('admin.orders.name') %> <%= content_tag :span, "(#{all_orders_count(@orders)})", :class => 'subtitle' %></h2>
      <div class="two columns">
        <div class="action-group">
          <ul class="horizontal right">
            <li><%= link_to t('admin.orders.actions.export'), admin_orders_path('xls', params) %></li>
          </ul>
        </div>
      </div>
      <div class="six columns">
        <div class="action-group">
          <%= form_tag admin_orders_path, :method => :get, :class => 'search-form row collapse', 'data-behavior' => 'table-filter' do %>
            <div class="three columns">
              <%= select_tag :payment_method, "<option value=\"\">#{t('activerecord.attributes.order.payment_method')}</option>".html_safe + options_for_select(Order.options_for_payment_method, params[:payment_method]), :class => 'select-field' %>
            </div>
            <div class="three columns">
              <%= select_tag :status, "<option value=\"\">#{t('activerecord.attributes.order.status')}</option>".html_safe + options_for_select(Order.options_for_status, params[:status]), :class => 'select-field' %>
            </div>
            <div class="six columns">
              <%= text_field_tag :search, params[:search], :placeholder => t('shared.placeholders.filter_table'), :class => 'search-keyword' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="twelve columns">
    <div class="orders-table-container">
      <table cellspacing="2" class="orders-table">
        <thead>
          <tr>
            <th class="two title"><%= t('activerecord.attributes.order.full_name') %></th>
            <th class="two"><%= t('shared.actions.name') %></th>
            <th class="text-centered two"><%= t('activerecord.attributes.order.product_count_short') %> / <%= t('activerecord.attributes.order.total_short') %></th>
            <th class="text-centered three"><%= t('activerecord.attributes.order.product_name') %></th>
            <th class="text-centered two"><%= t('activerecord.attributes.order.payment_method') %></th>
            <th class="text-centered one"><%= t('activerecord.attributes.order.created_at') %></th>
            <th class="text-centered one"><%= t('activerecord.attributes.order.payment_token_short') %></th>
          </tr>
        </thead>

        <tbody>
          <% if !@orders.empty? %>
            <% @orders.each do |order| %>
              <%= render order %>
            <% end %>
          <% else %>
            <tr>
              <td colspan="7">
                <div class="row empty-notice">
                  <div class="six columns centered">
                    <div class="flash-notice notice text-centered"><%= t('admin.orders.messages.notices.empty_orders') %></div>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="twelve columns text-centered">
      <div class="pagination-container">
        <%= page_navigation_links(@orders) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/update.js.erb
$('[data-order-id~=<%= @order.id %>]').attr('class', '<%= css_class_for_order_status @order %>');
$('[data-behavior~=new-orders-count]').html('<%= new_orders_count %>');
$('html').addClass('loaded');