config/routes.rb
Gaultmillau::Application.routes.draw do
  get "/current-user-meta" => "home#current_user_meta", :as => "home_current_user_meta"

  namespace :admin do
    resources :posts, :path => 'tartalommenedzser' do
      resources :blocks
      get :autocomplete_tag_name, :on => :collection
    end

    resources :home_blocks, :path => 'cimlapszerkeszto'
    resources :comments, :path => 'hozzaszolasok'
    resources :orders, :path => 'rendelesek', :only => [:index, :edit, :update, :destroy]
    resources :restaurant_reservations, :path => 'asztalfoglalasok', :only => [:index, :show, :destroy]
    resources :tags, :path => 'cimkek', :only => [:index, :destroy, :update, :edit, :show]
    resources :attachments, :path => 'mellekletek'
    resources :products, :path => 'termekek'
    resources :users, :path => 'felhasznalok' do
      member do
        get 'manual_confirm'
      end
    end

    post "/admin/home_blocks/sort" => "home_blocks#sort", :as => "sort_home_blocks"
    get "/admin/posts/:id/edit_post_meta" => "posts#edit_post_meta", :as => "edit_post_meta"
    post "/admin/blocks/sort" => "blocks#sort", :as => "sort_blocks"
    get "/admin/js/recipes_list" => "posts#recipes_list", :as => "recipes_list"
  end

  get "/admin" => "admin#index", :as => "admin_index"

  devise_for :users,
             :path => 'felhasznalok',
             :path_names => {
               :sign_up => 'regisztracio',
               :sign_in => 'bejelentkezes',
               :sign_out => 'kijelentkezes'
             }, :controllers => { :registrations => "registrations" }

  resources :products, :path => 'termekek', :only => [:show, :index] do
    resources :orders, :path => 'rendelesek', :only => [:create, :new, :index]
  end

  get 'rendelesek/:token', to: 'orders#show', as: :order

  resources :newsletter_subscriptions, :path => 'hirlevel'
  get 'hirlevel/jovahagyas/:id', to: 'newsletter_subscriptions#confirm', :as => 'confirm_newsletter_subscription'
  get 'hirlevel/leiratkozas/:id', to: 'newsletter_subscriptions#confirm_unsubscribe', :as => 'confirm_newsletter_unsubscribe'

  resources :feedbacks, :path => 'kapcsolat', :only => [:create]
  get 'kapcsolat', to: 'feedbacks#new', :as => 'new_feedback'

  resources :favourites, :path => 'kedvencek', :only => [:create, :update]

  get '/ettermek/legjobbak', to: 'restaurants#best_of_map', as: :best_of_restaurants_map
  get '/szallodak/legjobbak', to: 'hotels#best_of_map', as: :best_of_hotels_map
  get '/boraszatok/legjobbak', to: 'wineries#best_of_map', as: :best_of_wineries_map
  get '/ettermek/budapest-extra', to: 'restaurants#additional', as: :additional

  resources :restaurants, :path => 'ettermek' do
    get :autocomplete_restaurant_search_cache_name, :on => :collection
  end

  resources :hotels, :path => 'szallodak'
  resources :wineries, :path => 'boraszatok'

  resources :amuva_posts, :path => 'muvelt-alkoholista' do
    resources :amuva_comments
  end

  resources :bsz_posts, :path => 'buvos-szakacs' do
    resources :bsz_comments
  end

  resources :mh_posts, :path => 'mese-habbal' do
    resources :mh_comments
  end

  resources :news, :path => 'gm-magazin' do
    resources :news_comments
  end

  resources :restaurant_reservations, :path => 'ettermek/asztalfoglalas', :only => [:index, :new, :create]
  get 'asztalfoglalas/jovahagyas/:id', to: 'restaurant_reservations#confirm', :as => 'confirm_restaurant_reservation'

  get '/muvelt-alkoholista/cimke/:tag', to: 'amuva_posts#index', as: :amuva_tag
  get '/buvos-szakacs/cimke/:tag', to: 'bsz_posts#index', as: :bsz_tag
  get '/gm-magazin/cimke/:tag', to: 'news#index', as: :news_tag
  get '/mese-habbal/cimke/:tag', to: 'mh_posts#index', as: :mh_tag

  get '/feed', to: 'home#feed', as: :home_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista', to: 'amuva_posts#index', as: :amuva_feed, :defaults => { :format => 'rss' }
  get '/feed/muvelt-alkoholista/kommentek', to: 'amuva_comments#index', as: :amuva_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs', to: 'bsz_posts#index', as: :bsz_feed, :defaults => { :format => 'rss' }
  get '/feed/buvos-szakacs/kommentek', to: 'bsz_comments#index', as: :bsz_comments_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal', to: 'mh_posts#index', as: :mh_feed, :defaults => { :format => 'rss' }
  get '/feed/mese-habbal/kommentek', to: 'mh_comments#index', as: :mh_comments_feed, :defaults => { :format => 'rss' }

  resources :recipes, :path => 'receptek'

  get '/kereses', to: 'search#index', as: :search

  # Redirects
  get '/c/:id', to: 'short_urls#show', :as => 'short_url'
  get '/reg', to: redirect('felhasznalok/regisztracio')
  get '/regisztracio', to: redirect('felhasznalok/regisztracio')
  get '/bejelentkezes', to: redirect('felhasznalok/bejelentkezes')
  get '/fiok', to: redirect('felhasznalok/edit')
  get '/fiokom', to: redirect('felhasznalok/edit')
  get '/kod', to: redirect('a-gault-and-millau-2015-os-kalauz-nyomtatott-kuponkodjainak-bevaltasa')

  # Root and Pages

  get '/kalauz-2012/', to: 'guides2012#index', as: :guides2012
  get '/kalauz-2012/:id', to: 'guides2012#show', as: :guide2012
  get '/kalauz-2013/', to: 'guides2013#index', as: :guides2013
  get '/kalauz-2013/:id', to: 'guides2013#show', as: :guide2013
  get '/kalauz-2014/', to: 'guides2014#index', as: :guides2014
  get '/kalauz-2014/:id', to: 'guides2014#show', as: :guide2014
  get '/kalauz-2015/', to: 'guides2015#index', as: :guides2015
  get '/kalauz-2015/:id', to: 'guides2015#show', as: :guide2015
  get '/kalauz-2016/', to: 'guides2016#index', as: :guides2016
  get '/kalauz-2016/:id', to: 'guides2016#show', as: :guide2016
  get '/kalauz-2017/', to: 'guides2017#index', as: :guides2017
  get '/kalauz-2017/:id', to: 'guides2017#show', as: :guide2017
  get ':id', to: 'pages#show', as: :page

  root :to => "home#index"
end

app/controllers/bsz_posts_controller.rb
class BszPostsController < ApplicationController
  def index
    if params[:tag]
      @posts = Post.includes(:user, :attachment).bsz_public().tagged_with(params[:tag]).order('published_at DESC').paginate(:per_page => 12, :page => params[:page])
    else
      @posts = Post.includes(:user, :attachment).bsz_public().order('published_at DESC').paginate(:per_page => 12, :page => params[:page])
    end

    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.rss { render rss: @posts }
    end
  end

  def show
    if (user_signed_in? && current_user.role_admin) ||
       (user_signed_in? && current_user.role_editor) ||
       (user_signed_in? && current_user.role_senior_editor)
      @post = Post.bsz_posts.find_by_url(params[:id])
    else
      @post = Post.bsz_public.find_by_url(params[:id])
    end
  end
end

app/helpers/bsz_posts_helper.rb
module BszPostsHelper
  def render_bsz_footer
    render :partial => 'bsz_posts/footer'
  end

  def css_class_for_bsz_tag tag
    case tag
      when 'hozzávaló' then 'hozzavalo'
      when 'technológia' then 'technologia'
      when 'konyhariport' then 'konyhariport'
      when 'karizmatikus étel' then 'karizmatikus-etel'
      when 'gasztrokultúra' then 'gasztrokultura'
      when 'mge' then 'mge'
      else 'bsz-tag'
    end
  end
end

app/views/bsz_posts/_footer.html.erb
<footer class="row bsz-footer">
  <div class="twelve columns blog-navigation">
    <div class="inner">
      <ul>
        <li><%= link_to get_page_title('kulinaris-charta'), page_path('kulinaris-charta') %></li>
        <li><%= link_to get_page_title('charte-culinaire'), page_path('charte-culinaire') %></li>
        <li><%= link_to get_page_title('kulinarische-charta'), page_path('kulinarische-charta') %></li>
      </ul>
      <ul>
        <li><%= link_to get_page_title('a-buvos-szakacsrol'), page_path('a-buvos-szakacsrol') %></li>
        <li><%= link_to get_page_title('az-mge-alapszabalya'), page_path('az-mge-alapszabalya') %></li>
      </ul>
      <div class="about-bsz">
        <p>A Bűvös Szakácsot szerkeszti: Molnár B. Tamás és Bittera Dóra<br>
        A fotókat leggyakrabban Bittera Dóra készíti, a felhasználási jogot fenntartjuk. Ahol nem, ott jelöljük a fotós nevét.<br>
        A Bűvös Szakács 2008 óta a <%= link_to "Magyar Gasztronómiai Egyesület honlapja", bsz_tag_path('mge') %> is.</p>
      </div>
      <div class="panel mge-panel">
        <div class="row mge-container">
          <div class="four columns mge-logo">
            <%= image_tag 'logo-mge.png' %></p>
          </div>
          <div class="eight columns mge-contact">
            <p>Cím: 1011 Budapest, Szilágyi Dezső tér 1.</p>
            <p>Telefonszám: +36 70 370 7494</p>
            <p>Bankszámla: 11701004-20216348</p>
            <p>Adószám: 18116375-2-41</p>
            <p>A közhasznú egyesület várja mindazok hozzájárulását, akik adójuk 1%-át az egyesület céljaira kívánják fordítani</p>
          </div>
        </div>
      </div>
      <h3>Kedvenceink</h3>
      <% render_embedded_page('buvos-szakacs-kedvencek') %>
    </div>
  </div>
</footer>

app/views/bsz_posts/_header.html.erb
<header class="blog-header">
  <div class="row">
    <h2 class="eight columns centered">
      <%= link_to t('bsz.name'), bsz_posts_path, :class => 'blog-logo' %>
    </h2>
  </div>
</header>

<header class="row bsz-tags">
  <div class="twelve columns blog-navigation">
    <div class="inner">
      <ul>
        <% Post.main_bsz_categories.each do |tag| %>
          <li><%= link_to tag, bsz_tag_path(tag) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% render_embedded_page('bsz-fejlec-hirdetes') %>
</header>

app/views/bsz_posts/_post.html.erb
<article class="post <%= "post-tile six columns end" if params[:action] == 'index' %>">
  <div class="post-tile-inner">
    <%= link_to t('shared.actions.short_url'), get_short_url_for_post(post), :class => 'short-url', :title => t('shared.actions.short_url') %>
    <% if user_signed_in? %>
      <% if current_user.role_admin || current_user.role_senior_editor || current_user.role_editor %>
        <%= link_to t('shared.actions.edit'), edit_admin_post_path(post), :class => 'edit-post', :title => t('shared.actions.edit') %>
      <% end %>
    <% end %>
    <% cache ['v113', 'bsz', 'header', post] do %>
      <header class="post-header">
        <p class="main-tag-container">
          <% (post.tag_list & Post.main_bsz_categories).each do |tag| %>
            <%= link_to tag, bsz_tag_path(tag), :class => "main-tag #{css_class_for_bsz_tag(tag)}" %>
          <% end %>
        </p>
        <h1><%= link_to post.title, get_post_path_for(post) %></h1>
        <p class="post-meta">
          <time class="post-date"><%= l post.published_at, :format => :long %></time> &ndash;
          <% unless post.user.nil? %>
            <span class="post-author"><%= post.user.username %></span>
          <% end %>
          <% if !post.tag_list.empty? %>
            <%= link_to 'Tags', '#', :class => 'post-meta-icon post-tags-popover-toggle', 'data-behavior' => 'post-tags-popover-toggle' %>
          <% end %>
          <% if !post.not_commentable? %>
            <a href="<%= "#{get_post_path_for post}#comments" %>" class="post-meta-icon comments-count"><%= t('comment.titles.counter', :comments_count => number_for_comments(post.comments.count)).html_safe %></a>
          <% end %>
        </p>
        <% if !post.tag_list.empty? %>
          <ul class="plain popover post-tags-popover" data-behavior="post-tags-popover">
            <% post.tag_list.map do |tag| %>
              <li><%= link_to tag, bsz_tag_path(tag) %></li>
            <% end %>
          </ul>
        <% end %>
      </header>
    <% end %>
    <div class="post-body">
      <% if params[:action] == "show" %>
        <div class="share-actions">
          <div class="fb-like" data-href="<%= get_post_url_for post %>" data-send="false" data-layout="button_count" data-width="200" data-show-faces="false" data-action="recommend"></div>
        </div>
        <% @post.blocks.each do |block| %>
          <%= render :partial => 'blocks/block', :locals => { :post => @post, :block => block } %>
        <% end %>
      <% else %>
          <div class="row">
          <% if has_thumbnail_image?(post) %>
            <div class="twelve columns">
              <div class="featured-image" style="background-image: url('<%= thumbnail_image_for post %>'); background-color: <%= thumbnail_image_average_color_for(post) %>;">
              </div>
            </div>
          <% end %>
          <div class="<%= has_thumbnail_image?(post) ? 'twelve' : 'twelve' %> columns post-excerpt">
            <p>
            <%= clear_excerpt_field(post.excerpt) %><%= link_to "<span class=\"continue-to-post\">#{t('shared.actions.read_more')}</span>".html_safe, get_post_path_for(post), :class => 'read-more' %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</article>

app/views/bsz_posts/_sidebar.html.erb
<div class="three columns blog-sidebar">
  <h5><%= t('shared.titles.search') %></h5>
  <%= form_tag bsz_posts_path, method: :get do %>
    <%= text_field_tag :query, params[:query], :placeholder => t('shared.placeholders.search') %>
  <% end %>
  <h5><%= t('bsz.titles.tags') %></h5>
  <ul class="tags">
    <% tag_cloud Post.bsz_public().tag_counts, %w[tag tag tag] do |tag, css_class| %>
      <li><%= link_to tag.name, bsz_tag_path(tag.name), class: css_class %></li>
    <% end %>
  </ul>
</div>

app/views/bsz_posts/index.html.erb
<% content_for :title do %>
  <%= t('bsz.name') %> &ndash; <%= site_title %>
<% end  %>

<%= render :partial => 'bsz_posts/header' %>

<div class="row">
  <div class="twelve columns">
    <% if !@posts.empty? %>
      <div class="row post-tiles" data-behavior="post-tiles">
        <% @posts.each_with_index do |post, index| %>
          <%= render :partial => 'bsz_posts/post', :locals => { :post => post, :index => index } %>
        <% end %>
      </div>
      <div class="row">
        <div class="twelve columns text-centered">
          <div class="pagination-container">
            <%= page_navigation_links(@posts) %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="eight columns centered">
          <%= render :partial => 'shared/not_found', :locals => { :text => t('shared.messages.post_not_found') } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render_bsz_footer %>

app/views/bsz_posts/show.html.erb
<% content_for :title do %>
  <%= @post.title %> &ndash; <%= t('bsz.name') %> &ndash; <%= site_title %>
<% end  %>
<% content_for(:og_description) { @post.excerpt } %>
<% content_for(:og_type) { "article" } %>
<% if has_thumbnail_image?(@post) %>
  <% content_for(:og_image) { thumbnail_image_for @post } %>
<% end %>

<%= render :partial => 'bsz_posts/header' %>

<div class="row">
  <div class="eight columns centered">
    <%= render :partial => 'bsz_posts/post', :locals => { :post => @post } %>
    <% if !@post.not_commentable? %>
      <div class="comments" id="comments">
        <h3 class="comments-title" data-behavior="comments-counter">
          <% if @post.comments.count == 0 %>
            <%= t('comment.titles.empty_counter') %>
          <% else %>
            <%= t('comment.titles.form_counter', :comments_count => @post.comments.size) %>
          <% end %>
          <div class="share-actions right">
            <div class="fb-like" data-href="<%= get_post_url_for @post %>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" data-action="recommend"></div>
          </div>
        </h3>
        <% if !user_signed_in? %>
          <p class="info-panel"><%= t('comment.titles.not_logged_in', :new_registration_path => new_user_registration_path).html_safe %></p>
        <% end %>
        <% @post.comments.reverse.each do |comment| %>
          <%= render :partial => 'bsz_comments/comment', :locals => { :comment => comment } %>
        <% end %>
        <% if user_signed_in? %>
          <%= render 'bsz_comments/form' %>
        <% end %>
     </div>
    <% end %>
  </div>
</div>

<%= render_bsz_footer %>